import Head from 'next/head';
import * as S from '../../../styles/shared';

import DiffChart from '../../ui/DiffChart';

export default function Index() {
  return (
    <>
      <Head>
        <title>Realizze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="container">
          <div className="grid">
            <div className="col-12 mt-5">
              <S.Card>
                <DiffChart />
              </S.Card>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
