import Head from 'next/head';

import * as S from '@/styles/shared';

export default function Investments() {
  return (
    <>
      <Head>
        <title>Realizze</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="grid">
          <div className="col-12 mt-5">
            <S.Card>
              <div className="grid">
                <div className="col">
                  <S.Title className="mb-2">Investimentos</S.Title>
                </div>
              </div>
            </S.Card>
          </div>
        </div>
      </div>
    </>
  );
}
